sonar.projectKey=ashish-cisco_webex-widgets
sonar.organization=ashish-cisco
sonar.projectName=webex-widgets
sonar.sources=packages
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=8192
sonar.javascript.node.debugMemory=true
sonar.javascript.createTSProgramForOrphanFiles=false
sonar.typescript.tsconfigPaths=packages/contact-center/ai-assistant/tsconfig.json,packages/contact-center/cc-components/tsconfig.json,packages/contact-center/cc-digital-channels/tsconfig.json,packages/contact-center/cc-widgets/tsconfig.json,packages/contact-center/station-login/tsconfig.json,packages/contact-center/store/tsconfig.json,packages/contact-center/task/tsconfig.json,packages/contact-center/test-fixtures/tsconfig.json,packages/contact-center/ui-logging/tsconfig.json,packages/contact-center/user-state/tsconfig.json
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.js.map,**/*.min.js,**/*.bundle.js,**/docs/**
